# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Scribe"
license = "MIT"
licenselink = "https://github.com/laurannehery/scribe/blob/master/LICENSE.md"
description = "Personal theme"
homepage = "http://www.laurannehery.fr/"
tags = ["portfolio", "grid"]
min_version = 0.18

[author]
  name = "Lauranne Héry"
  homepage = "http://www.laurannehery.fr/"
